### ISSUE TITLE
Cannot select Channel

### ISSUE THREAD

**Issue by 516wjy** [ohmysh/ohmysh#19]
**Describe the bug**
No response after oms —channel dev

**To Reproduce**
oms —channel dev

**System Information**
 - OS: Arch Linux
 - Shell: bash
 - OhMySh version: 0.0.7-build_46

**Comment by langonginc** [comment]
This bug has fixed in dev channel.
Please select channel manually.

**Comment by 516wjy** [comment]
In https://github.com/ohmysh/ohmysh/commit/fd2e1e1f064fa9e5b9f41c22ba99c50198fc25f8 , it appears again.
