### ISSUE TITLE
Update error (in both stable and dev channel)

### ISSUE THREAD

**Issue by langonginc** [ohmysh/ohmysh#20]
**Describe the bug**
- Updates from forward commits
- Failed to catch proper tag 

**System Information**
 - OS: Linux-*
 - Shell: *
 - OhMySh version: 0.0.7-build_47.220430, https://github.com/ohmysh/ohmysh/commit/ae0cfc0a6ccf1556541c35124e6fd3e7134d9ca2 , 74d50f9d5d028fd6eb7fea1371337b4408d041c6

**Comment by langonginc** [comment]
We strongly suggest all in dev to go back to build_47.

**Comment by 516wjy** [comment]
#19 appears again
