### ISSUE TITLE
The command tree don't print a tree struct context in oms.

### ISSUE THREAD

**Issue by Ircon** [ohmysh/ohmysh#21]
# Describe the bug
## Environment
the system version is Ubuntu 18.06 LTS in wsl 2. The system in  physics computer is Windows11.

## Before installing oms
input tree command and will print like this.
![image](https://user-images.githubusercontent.com/11171522/177070218-b68f216d-679e-412d-93d1-4b1fb4bd9628.png)

## After installing oms
input tree command and will print like this.
![image](https://user-images.githubusercontent.com/11171522/177070287-2515f344-363b-477a-a83f-fa299e739347.png)

## Summary
How to make tree print context which is a tree like that I did't install oms.

# Others
I only instal the oms with the default configure from gitee -- the chinese mirror.
There are not any changes in configure after intalling oms.

**Comment by langonginc** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/59787082/177508905-7632ac39-f2e4-4a15-8a96-06109bd7a046.png">

The script enabled `tree` command for `ls -R` normally, you can disable `mapMSDos` in the advanced configuration file.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/59787082/177509478-ca95cd09-4cfb-4552-a6e8-6483183c63e2.png">

Here are some simple steps:

1. open your terminal and run this command `oms -e vim` (if you can use the editor `vim`, or you can replace the editor name)
2. uncomment the line which is named `mapMSDos`.
3. save the file.
4. reload oms by run `oms -r`.

We will fix the conflict issue later. Thank you very much.

**Comment by Ircon** [comment]
Thank you, I fixed it.

**Comment by langonginc** [comment]
Thank you too.
