### ISSUE TITLE
Double quote to prevent globbing and word splitting.

### ISSUE THREAD

**Issue by langonginc** [ohmysh/ohmysh#8]
#### Occurred on:
+ **Commit**:  a54e88ef01217fa74a4cf24c26067c7741af4c67
+ **File**:    [lib/trash.sh](https://github.com/ohmysh/ohmysh/blob/a54e88ef01217fa74a4cf24c26067c7741af4c67/lib/trash.sh)
+ **LineNum**: [89](https://github.com/ohmysh/ohmysh/blob/a54e88ef01217fa74a4cf24c26067c7741af4c67/lib/trash.sh#L89)
+ **Code**:    `_rmlist=($(find "$OMS_CACHE/trash" -maxdepth 1 -printf "%f\n" | grep $NP))`

    
#### Currently on:
+ **Commit**:  a54e88ef01217fa74a4cf24c26067c7741af4c67
+ **File**:    [lib/trash.sh](https://github.com/ohmysh/ohmysh/blob/a54e88ef01217fa74a4cf24c26067c7741af4c67/lib/trash.sh)
+ **LineNum**: [89](https://github.com/ohmysh/ohmysh/blob/a54e88ef01217fa74a4cf24c26067c7741af4c67/lib/trash.sh#L89)

**Comment by 516wjy** [comment]
```bash
            _rmlist=()
            find "$OMS_CACHE/trash" -maxdepth 1 -printf "%f\n" | grep $NP | while IFS= read -r i
            do
                _rmlist+=("$i")
            done
```

**Comment by langonginc** [comment]
not working...
